import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "../app/_component/navbar/Navbar"; 
import { Toaster } from "../../@/components/ui/Toaster"; 
import MySessionProvider from "./_component/navbar/MySessionProvider/MySessionProvider";
import { WishlistProvider } from "../context/WishlistContext";
import { CartProvider } from "../context/CartContext"; 
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { toast } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

(toast as any).add = ({ title, type, TIMEOUT }: { title: string; type: string; TIMEOUT?: number }) => {
  if (type === "success") {
    toast.success(title, { duration: TIMEOUT || 2000 });
  } else if (type === "error") {
    toast.error(title, { duration: TIMEOUT || 2000 });
  } else {
    toast(title, { duration: TIMEOUT || 2000 });
  }
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen bg-background font-sans">
        <header className="flex justify-center"></header>

        <MySessionProvider>
          <CartProvider>
            <WishlistProvider>
              <Navbar />
              {children}
              <Toaster />
            </WishlistProvider>
          </CartProvider>
        </MySessionProvider>
        <ToastContainer />
      </body>
    </html>
  );
}